Core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('step.urls')),
    # path('', include('webapp.urls')),
    # path('', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dilidi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

step/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'step'

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('perfil/', views.perfil,name='perfil'),
    path('registar/', views.registar, name='registar'),
    path('dasboard/', views.dasboard, name='dasboard'),
    path('entidades/', views.entidades, name='entidades'),
    path('entidades/add/', views.addentidades, name='addEntidades'),
    path('entidade/<int:pk>/editar/', views.editarentidades, name='editarEntidades'),
    path('entidade/<int:pk>/eliminar/', views.deleteEntidade, name='eliminarEntidade'),
    path('projectos/', views.projectos, name='projectos'),
    path('projecto/add/', views.addProjecto, name='addprojecto'),
    path('projecto/<int:pk>/editar/', views.editarProjecto, name='editarProjecto'),
    path('projecto/<int:pk>/eliminar/', views.deleteProjecto, name='eliminarProjecto'),
   
    path('categorias/', views.categorias, name='categorias'),
    path('categoria/add/', views.addCategoria, name='addCategoria'),
    path('categoria/<int:pk>/editar/', views.editarCategoria, name='editarCategoria'),
    path('categoria/<int:pk>/eliminar/', views.deleteCategoria, name='eliminarCategoria'),
    
    path('login/', auth_views.LoginView.as_view(template_name='step/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

step/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


# from django.urls import reverse

class Perfil(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    imagem = models.ImageField(default='default.jpg',upload_to='ImgPerfil')

    def __str__(self):
        return f'Perfil - {self.user.username}'

    def save(self, *args, **kwargs):
        super().save(*args,**kwargs)

        img = Image.open(self.imagem.path)

        if img.height > 300 or img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.imagem.path)

class Categorias(models.Model):
    nome = models.CharField(max_length=50, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    dataRegisto = models.DateTimeField(auto_now_add=True)
    dataModificacao = models.DateTimeField(auto_now=True)
    


    def __str__(self):
        return f'{self.nome}'

class Entidades(models.Model):
    nome = models.CharField(max_length=100, null=False)
    email = models.EmailField(max_length=100, null=False)
    contacto = models.CharField(max_length=50, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.nome}'
    
class Projectos(models.Model):
    ops = [('Parado', 'Parado'),('Concluído', 'Concluído'), ('Em produção', 'Em produção')]
    categoria = models.ForeignKey(Categorias, on_delete=models.CASCADE)
    descricao = models.CharField(max_length=100, default=None)
    custos = models.IntegerField(default='0')
    dataEntrega = models.DateField(default=None, null=True)
    dataRegisto = models.DateTimeField(auto_now=True)
    estado = models.CharField(max_length=100, null=False, default='prado', choices=ops)
    projecto = models.FileField(upload_to='Projectos', default=None, blank=True, null=True)
    progresso = models.IntegerField(default='0')
    dataConclusao = models.DateField(default=None, null=True, blank=True)
    entidade = models.ForeignKey(Entidades, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Notificacoes(models.Model):
    titulo = models.CharField(max_length=100, null=False)
    categoria = models.CharField(max_length=100, null=False)
    projecto = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


    # def __repr__(self):
    #     return f"Notificações('{self.titulo}','{self.idUser}')"

step/views/categorias.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django import forms

from step.models import Categorias


class FormCategoria(forms.ModelForm):
    class Meta:
        model = Categorias
        fields = ['nome', ]


@login_required
def categorias(request):
    context = {
        "categorias": Categorias.objects.filter(user=request.user)
        }
    return render(request, 'step/categorias.html', context)


@login_required
def addCategoria(request):
    
    print(request.POST)
    if request.method == 'POST':
        form = FormCategoria(request.POST,)
        form.instance.user = request.user

        # Validar o formulario
        if form.is_valid():
            form.save()
            nome = form.cleaned_data.get('nome')
            messages.success(
                request, f'Categoria "{nome}" criada com sucesso!')
            return redirect('step:categorias')
        else:
            messages.error(
                request, f'{form.errors}', extra_tags='danger')
    else:
        form = FormCategoria()
    return render(request, 'step/categorias.html', {'form': form})


@login_required
def editarCategoria(request, pk):
    obj = get_object_or_404(Categorias, pk=pk)
    print(request.POST)
    if request.method == 'POST':
        form = FormCategoria(request.POST, instance=obj)
        form.instance.user = request.user

        # Validar o formulario
        if form.is_valid():
            form.save()
            nome = form.cleaned_data.get('nome')
            messages.success(
                request, f'Categoria "{nome}" editada com sucesso!')
            return redirect('step:categorias')
        else:
            messages.error(
                request, f'{form.errors}', extra_tags='danger')
    else:
        form = FormCategoria(instance=obj)
    return render(request, 'step/categorias.html', {'form': form})


@login_required
def deleteCategoria(request, pk):
    obj = get_object_or_404(Categorias, pk=pk)
    obj.delete()
    # Criar mensagem de sucesso, pois a operação foi efectuada com sucesso.
    messages.success(
        request, f'Categoria "{obj.nome}" eliminada com sucesso!')
    return redirect('step:categorias')

step/views/dasboard.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from step.models import Notificacoes, Projectos

@login_required
def dasboard(request):
    # idUser = current_user.id
    # pr_parados = Projectos.query.filter_by(idUsuario=idUser,estado="parado").count()
    # pr_producao = Projectos.query.filter_by(idUsuario=idUser,estado="em produção").count()
    # pr_concluido = Projectos.query.filter_by(idUsuario=idUser,estado="concluído").count()
    # pr_total = Projectos.query.filter_by(idUsuario=idUser).count()
    # gr_Projectos = {'total': pr_total,'parados': pr_parados, 'producao': pr_producao, 'concluidos': pr_concluido}

    # alert = Notificacoes.query.filter_by(idUser=current_user.id).all()

    context = {
        'total': Projectos.objects.filter(user=request.user).count(),
        'parados': Projectos.objects.filter(user=request.user, estado='Parado').count(),
        'producao': Projectos.objects.filter(user=request.user, estado='Em produção').count(),
        'concluidos': Projectos.objects.filter(user=request.user, estado='Concluído').count(),
        'alert': Notificacoes.objects.order_by('-id').filter(user=request.user)[:4],
    }
    return render(request, 'step/dasboard.html', context)

step/views/entidades.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django import forms

from step.models import Entidades


class FormEntidade(forms.ModelForm):
    class Meta:
        model = Entidades
        fields = ['nome', 'email', 'contacto',]


@login_required
def entidades(request):
    context = {
        "result": Entidades.objects.filter(user=request.user),
        }
    # e = Entidades.objects.first()
    # e.projectos.all()
    return render(request, 'step/entidades.html', context)


@login_required
def addentidades(request):
    
    print(request.POST)
    if request.method == 'POST':
        form = FormEntidade(request.POST,)
        form.instance.user = request.user

        # Validar o formulario
        if form.is_valid():
            form.save()
            nome = form.cleaned_data.get('nome')
            messages.success(
                request, f'Entidade "{nome}" criado com sucesso!')
            return redirect('step:entidades')
        else:
            messages.error(
                request, f'{form.errors}', extra_tags='danger')
    else:
        form = FormEntidade()
    return render(request, 'step/entidades.html', {'form': form})


@login_required
def editarentidades(request, pk):
    obj = get_object_or_404(Entidades, pk=pk)
    print(request.POST)
    if request.method == 'POST':
        form = FormEntidade(request.POST, instance=obj)
        form.instance.user = request.user

        # Validar o formulario
        if form.is_valid():
            form.save()
            nome = form.cleaned_data.get('nome')
            messages.success(
                request, f'Entidade "{nome}" editada com sucesso!')
            return redirect('step:entidades')
        else:
            messages.error(
                request, f'{form.errors}', extra_tags='danger')
    else:
        form = FormEntidade(instance=obj)
    return render(request, 'step/entidades.html', {'form': form})


@login_required
def deleteEntidade(request, pk):
    obj = get_object_or_404(Entidades, pk=pk)
    obj.delete()
    # Criar mensagem de sucesso, pois a operação foi efectuada com sucesso.
    messages.success(
        request, f'Entidade "{obj.nome}" eliminada com sucesso!')
    return redirect('step:entidades')

step/views/index.py
from django.shortcuts import render


def index(request):
    return render(request, 'step/index.html',)

step/views/perfil.py
from django.shortcuts import render
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from step.models import Perfil


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username','email'] 
        
class PerfilUpdateForm(forms.ModelForm):    
    class Meta:
        model = Perfil
        fields = ['imagem'] 


def registar(request):
    """
    Registar Usuário.
    """
    if request.method=='POST':
        # Formulario de registar usuario
        form = UserRegisterForm(request.POST)
        # Validar o formulario de registar usuario
        if form.is_valid():
            form.save()
            
            username = form.cleaned_data.get('username')
            messages.success(request,f'A sua conta foi criada, agora podes fazer o login.')
            return redirect('step:login')
    else:
        form = UserRegisterForm()
    
    return render(request,'step/registar.html',{'form':form})

@login_required
def perfil(request):
    if request.method=='POST':
        form_user = UserUpdateForm(request.POST, instance=request.user)
        form_perfil = PerfilUpdateForm(request.POST, request.FILES , instance=request.user.perfil)

        #Verificar se os formulários são válidos 
        if form_user.is_valid() and form_perfil.is_valid():
            form_user.save()
            form_perfil.save()
            messages.success(request,f'Perfil actualizado com sucesso.')
            return redirect('step:perfil')
    else:
        form_user = UserUpdateForm(instance=request.user)
        form_perfil = PerfilUpdateForm(instance=request.user.perfil)
        
    context = {
        'form_user': form_user,
        'form_perfil': form_perfil,
        'title': 'Perfil',
    }
    return render(request,'step/perfil.html',context)

step/views/projectos.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django import forms

from step.models import Entidades, Notificacoes, Projectos, Categorias

class FormProjecto(forms.ModelForm):
    # model_to_filter = CustomModelFilter(queryset=CustomModel.objects.filter(active=1))
    class Meta:
        model = Projectos
        fields = ['descricao', 'custos', 'dataEntrega', 'estado',
                  'progresso', 'projecto']

        widgets = {
            'dataEntrega': forms.DateInput(attrs={
                'class': 'form-control',
                'type': 'date'}),
        }
        


@login_required
def projectos(request):
    context = {
        'projectos': Projectos.objects.filter(user=request.user)
        }
    return render(request, 'step/projectos.html', context)


@login_required
def addProjecto(request):
    entidade = None
    categorias = Categorias.objects.filter(user=request.user)
    if request.method== 'GET':
        entidade = Entidades.objects.get(pk=request.GET['en'])
        
    form = FormProjecto()
    form.instance.entidade = entidade
    
    
    if request.method == 'POST':
        form = FormProjecto(request.POST, request.FILES,)
        form.instance.user = request.user
        entidade = Entidades.objects.get(pk=request.POST['idEntidade'])
        form.instance.entidade = entidade
        form.instance.categoria = Categorias.objects.get(pk=request.POST['categoria'])
        
        # Validar o formulario
        if form.is_valid():
            form.save()
            # descricao = form.cleaned_data.get('descricao')
            descricao = request.POST['descricao']
            messages.success(
                request, f'Projecto "{descricao}" criado com sucesso!')
            # create_notificacao = Notificacoes(titulo=titulo_not,categoria='info',projecto=form.descricao.data,idUser=current_user.id)
            titulo_not = f"Novo Projecto! Foi adicionado recentemente o projecto {descricao}."
            notification = Notificacoes(titulo=titulo_not, categoria='info', projecto=descricao, user=request.user)
            notification.save()
            return redirect('step:projectos')
        else:
            messages.error(
                request, f'{form.errors}', extra_tags='danger')

    context = {'form': form, 'entidade': entidade, 'categorias': categorias}
    return render(request, 'step/addprojectos.html', context)


@login_required
def editarProjecto(request, pk):
    categorias = Categorias.objects.filter(user=request.user)
    obj = get_object_or_404(Projectos, pk=pk)
    if request.method == 'POST':
        obj = get_object_or_404(Projectos, pk=pk)
        form = FormProjecto(request.POST, request.FILES, instance=obj)
        form.instance.pk = obj.pk
        form.instance.user = obj.user
        form.instance.entidade = obj.entidade
        form.instance.categoria = Categorias.objects.get(pk=request.POST['categoria'])
        
        # Validar o formulario
        if form.is_valid():
            form.save()
            descricao = form.cleaned_data.get('descricao')
            messages.success(
                request, f'Projecto "{descricao}" editado com sucesso!')
            return redirect('step:projectos')
        else:
            messages.error(
                request, f'{form.errors}', extra_tags='danger')
    else:
        form = FormProjecto(instance=obj)

    context = {'form': form, 'entidade': obj.entidade, 'categorias': categorias, 'categoriaS': obj.categoria.pk}
    return render(request, 'step/editarprojectos.html', context)




@login_required
def deleteProjecto(request, pk):
    obj = get_object_or_404(Projectos, pk=pk)
    obj.delete()
    # Criar mensagem de sucesso, pois a operação foi efectuada com sucesso.
    messages.success(
        request, f'Projecto "{obj.descricao}" eliminada com sucesso!')
    return redirect('step:projectos')

step/templates/step/alerts.html
{% if messages %} {% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
    ×
  </button>
  <i class="fa fa-info-circle"></i> {{ message }}
</div>
{% endfor %} {% endif %} {% block content %} {% endblock content %}

<!-- <div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
    ×
  </button>
  <i class="fa fa-info-circle"></i> {{ message }}
</div> -->

step/templates/step/baseAdmin.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta
      content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
      name="viewport"
    />

    <!-- bootstrap 3.0.2 -->
    <link
      href="{% static 'step/css/bootstrap.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{% static 'step/font-awesome/css/font-awesome.css' %}"
      rel="stylesheet"
      type="text/css"
    />

    <link
      href="{% static 'step/css/mystyle.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{% static 'step/css/style.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <!-- <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    /> -->

    {% if title %}
    <title>{{title}}</title>
    {% else %}
    <title>STEP</title>
    {% endif %}
  </head>
  <body class="skin-black">
    <!-- header logo: style can be found in header.less -->
    <header class="header">
      <a href="{% url 'step:index' %}" class="logo">
        <!-- Add the class icon to your logo image or logo icon to add the margining -->
        STEP
      </a>
      <!-- Header Navbar: style can be found in header.less -->
      <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a
          href="#"
          class="navbar-btn sidebar-toggle"
          data-toggle="offcanvas"
          role="button"
        >
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <!-- tasks-menu -->
        <div class="navbar-right">
          <ul class="nav navbar-nav">
            <li class="dropdown tasks-menu"></li>
            <!-- User Account: style can be found in dropdown.less -->
            <li class="dropdown user user-menu">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-user"></i>
                <span> {{user.username}} <i class="caret"></i></span>
              </a>
              <ul class="dropdown-menu dropdown-custom dropdown-menu-right">
                <li class="dropdown-header text-center">Conta</li>

                <li class="divider"></li>

                <li>
                  <a href="{% url 'step:perfil' %}">
                    <i class="fa fa-user fa-fw pull-right"></i>
                    Perfil
                  </a>
                </li>
                <li class="divider"></li>
                <li>
                  <a href="{% url 'step:logout' %}"
                    ><i class="fa fa-ban fa-fw pull-right"></i>Sair</a
                  >
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </nav>
    </header>

    <div class="wrapper row-offcanvas row-offcanvas-left">
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="left-side sidebar-offcanvas">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
          <div class="user-panel">
            <div class="pull-left image">
              <img
                src="{{user.perfil.imagem.url}}"
                class="img-circle"
                alt="User Image"
              />
            </div>
            <div class="pull-left info">
              <p>Olá, {{current_user.nome}}</p>

              <a href="#"><i class="fa fa-circle text-success"></i> Activo</a>
            </div>
          </div>

          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu">
            <li>
              <a href="{% url 'step:dasboard' %}">
                <i class="fa fa-dashboard"></i> <span>Painel de controle </span>
              </a>
            </li>
            <li>
              <a href="{% url 'step:projectos' %}">
                <i class="fa fa-dropbox"></i> <span>Projectos</span>
              </a>
            </li>

            <li class="">
              <a href="{% url 'step:entidades' %}">
                <i class="fa fa-group"></i> <span>Entidades</span>
              </a>
            </li>

              <li class="">
              <a href="{% url 'step:categorias' %}">
                <i class="fa fa-tasks"></i> <span>Categorias</span>
              </a>
            </li>
          </ul>
        </section>
        <!-- /.sidebar -->
      </aside>

      <!-- Right side column. Contains the navbar and content of the page -->
      <aside class="right-side">
        <!-- Main content -->
        <section class="content">
          {% block content %} {% endblock content %}
        </section>
      </aside>
      <!-- /.right-side -->
    </div>
    <!-- ./wrapper -->

    <!-- jQuery 2.0.2 -->
    <script
      src="{% static 'step/js/jquery.min.js' %}"
      type="text/javascript"
    ></script>
    <script
      src="{% static 'step/js/bootstrap.min.js' %}"
      type="text/javascript"
    ></script>
    <script src="{% static 'step/js/app.js' %}" type="text/javascript"></script>
    <script src="{% static 'step/js/dsajax.js' %}"></script>
    <script src="{% static 'step/js/stepjs.js' %}"></script>

    {% block individualScript %} {% endblock individualScript %}
  </body>
</html>

step/templates/step/entidades.html
{% extends 'step/baseAdmin.html' %} {% load static %} {% block content %}
<div class="row">
  <div class="col-md-12">
    <!--breadcrumbs start -->
    <ul class="breadcrumb">
      <li class="active">Menu de Entidades</li>
      <li>
        <a style="color: rgb(95, 93, 93)"
          ><i class="fa fa-plus-circle"></i> Adicionar
        </a>
      </li>
    </ul>
    <!--breadcrumbs end -->
  </div>

  <div class="col-lg-12">{% include "step/alerts.html" %}</div>

  <!-- Pesquisar Entidade -->
  <div class="col-md-12">
    <form method="get">
      <div class="box-tools m-b-15">
        <div class="input-group">
          <input
            type="text"
            name="search"
            value="{{search}}"
            class="form-control input-sm pull-right"
            autocomplete="off"
            style="width: 250px"
            placeholder="Search"
          />
          <div class="input-group-btn">
            <button class="btn btn-sm btn-default">
              <i class="fa fa-search"></i>
            </button>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

<!-- Entidades -->
<div class="row">
  <!-- formulario -->
  <div class="col-lg-4">
    <section class="panel">
      <header class="panel-heading">Formulário</header>
      <div class="panel-body">
        <!-- formulário de criação de conta -->
        <form role="form" method="POST" action="{% url 'step:addEntidades' %}">
          {% csrf_token %}

          <!-- Nome -->
          <div class="form-group">
            <input
              type="text"
              name="nome"
              class="form-control"
              value="{{form.nome.value}}"
              placeholder="Nome"
              autocomplete="off"
            />
          </div>

          <!-- email -->
          <div class="form-group">
            <input
              type="email"
              name="email"
              value="{{form.email.value}}"
              class="form-control"
              placeholder="email"
              autocomplete="off"
            />
          </div>

          <!-- contacto -->
          <div class="form-group">
            <input
              type="text"
              name="contacto"
              value="{{form.contacto.value}}"
              class="form-control"
              placeholder="contacto"
              autocomplete="off"
            />
          </div>

          <!-- Adicionar -->
          <div class="form-group">
            <button type="submit" class="btn btn-info" style="margin-left: 5px">
              Salvar
            </button>
            <button
              type="reset"
              id="btnCancelar"
              class="btn btn-danger hidden"
              style="margin-left: 5px"
            >
              Cancelar
            </button>
          </div>
        </form>
      </div>
    </section>
  </div>

  <!-- Tabela de Entidades -->
  <div class="col-md-8">
    <section class="panel">
      <header class="panel-heading">Entidades Registadas</header>

      <div
        class="panel-body table-responsive"
        style="max-height: 420px; overflow: auto"
      >
        <table class="table table-hover" id="tbEntidades">
          <thead>
            <tr>
              <th>ID</th>
              <th>Nome</th>
              <th>Email</th>
              <th>Contacto</th>
              <th>Projectos</th>
              <th>Ações</th>
            </tr>
          </thead>
          <tbody>
            
            {% if result %} {% for dados in result%}
            <tr>
              <td>{{ dados.id }}</td>
              <td>{{ dados.nome }}</td>
              <td>{{ dados.email }}</td>
              <td>{{ dados.contacto }}</td>
              <td>{{ dados.projectos_set.count}}</td>

              <td>
                <a onclick="PassarDados('/entidade/{{dados.id}}/editar/')"
                  ><button class="btn btn-default btn-xs">
                    <i class="fa fa-pencil"></i></button
                ></a>
                <a
                  onclick="fnIdselecionado('/entidade/{{dados.id}}/eliminar/')"
                  data-toggle="modal"
                  data-target="#ModalConfirm"
                  ><button class="btn btn-default btn-xs">
                    <i class="fa fa-times"></i></button
                ></a>
                <a href="/projecto/add/?en={{dados.id}}"
                  ><button class="btn btn-default btn-xs">
                    <i
                      class="fa fa-plus-circle"
                      title="Adicionar Projecto"
                    ></i></button
                ></a>
              </td>
            </tr>
            {% endfor %} {% endif %}
          </tbody>
        </table>
      </div>
    </section>

    {% comment %}
    <!-- Paginação -->
    <!-- <div class="text-left" style="margin-top: -34px;">
                <ul class="pagination">
                    <li><a href="#">«</a></li>
                {% for numPage in result.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2)%}
                    {% if numPage %}
                        {% if result.page == numPage %}
                            <li><a style="background-color: #ccc;" href="{{ url_for('entidads.entidades', page=numPage) }}">{{ numPage }}</a></li>
                        {% else %}
                            <li><a href="{{ url_for('entidads.entidades', page=numPage) }}">{{ numPage }}</a></li>
                        {% endif %}
                    {% endif %}
                {% endfor %}
                        <li><a href="#">»</a></li>
                </ul>
    </div> -->
    {% endcomment %}
  </div>

  <!-- Modal -->
  <div class="col-lg-4">
    <div class="row">
      <div class="col-md-4">
        <section class="panel">
          <!-- ModalInformacao -->
          <div
            class="modal fade"
            id="ModalInformacao"
            tabindex="-1"
            role="dialog"
            aria-labelledby="myModalLabel"
            aria-hidden="true"
          >
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button
                    type="button"
                    class="close"
                    data-dismiss="modal"
                    aria-hidden="true"
                  >
                    ×
                  </button>
                  <h4 class="modal-title">Informações Adicionais</h4>
                </div>
                <div class="modal-body">Corpo do Modal</div>
                <div class="modal-footer">
                  <button
                    data-dismiss="modal"
                    class="btn btn-default"
                    type="button"
                  >
                    Close
                  </button>
                </div>
              </div>
            </div>
          </div>

          <!-- ModalConfirm -->
          <div
            class="modal fade"
            id="ModalConfirm"
            tabindex="-1"
            role="dialog"
            aria-labelledby="myModalLabel"
            aria-hidden="true"
          >
            <div class="modal-dialog modal-sm" style="display: flex">
              <div
                class="modal-content col-md-8"
                style="margin-left: 20%; margin-top: 10%"
              >
                <div class="modal-header">
                  <button
                    type="button"
                    class="close"
                    data-dismiss="modal"
                    aria-hidden="true"
                  >
                    ×
                  </button>
                  <h4 class="modal-title">Atenção</h4>
                </div>
                <div class="modal-body">
                  Estás prestes a eliminar este projecto, desejas continuar com
                  a operação?
                </div>
                <div class="modal-footer">
                  <a class="btn btn-info" id="btnConfirm">Sim</a>
                  <button data-dismiss="modal" class="btn btn-default">
                    Não
                  </button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</div>

{% endblock content %} {% block individualScript %}
<script src="{% static 'step/js/step/entidades.js' %}"></script>
{% endblock individualScript %}